name: Build, publish and deploy project to Simply

on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        working-directory: NATSInternal
        run: dotnet restore

      - name: Build
        working-directory: NATSInternal
        run: dotnet build --configuration Debug --no-restore
        
      - name: List Build Directory
        run: |
          echo "Listing NATSInternal/bin directory:"
          ls -R NATSInternal/bin/Debug/net8.0/ || echo "NATSInternal/bin/Debug/net8.0/ directory does not exist."


      - name: Prepare Deployment Directory
        run: |
          mkdir -p ./deploy
          cp -r ./NATSInternal/bin/Debug/net8.0/* ./deploy/
          cp -r ./NATSInternal/wwwroot ./deploy/

      - name: Publish
        working-directory: NATSInternal
        run: dotnet publish --configuration Debug

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win8125.site4now.net
          username: nh0zhuybmt-001
          password: Huyy47b1
          local-dir: ./deploy/

      # - name: Deploy to Simply        
      #   uses: talunzhang/auto-web-deploy@v1.0.1
      #   with:
      #     website-name: natsinternal.khanhhuy.dev
      #     server-computer-name: https://win8125.site4now.net:8172
      #     server-username: nh0zhuybmt-001
      #     server-password: Huyy47b1
      #     source-path: NATSInternal\bin\Debug\net8.0\publish\
          
      - name: Migrate
        working-directory: NATSInternal
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update --connection "Server=mysql8001.site4now.net;Database=db_aa5821_natsint;Uid=aa5821_natsint;Password=Huyy47b1;SSL Mode=None"
